#!/usr/bin/env python

# Silly utility to find the "best" accessible address for a machine. Given a
# port and a list of hostnames which are considered to be equivalent, find the
# first one that is accessible and return it.

# Author: Tim Creech <tcreech@umd.edu>

import socket
import sys
import string

if ( len(sys.argv) <= 2 ):
   print "Usage: " + sys.argv[0] + " [tcp_port] [hostname1 ...]"
   print "\tHostnames will be tried in order on the given port. The first to respond will be printed."
   sys.exit(1)


remote_port = string.atoi(sys.argv[1])
remote_hosts = sys.argv[1:]

for remote_host in remote_hosts:

   sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
   sock.settimeout(2)
   try:
      sock.connect((remote_host, remote_port))
   except Exception,e:
      pass
   else:
      print remote_host
      sys.exit(0)
   sock.close()

sys.exit(1)

